tasks:
  - command: ./start-demo.sh
ports:
  - name: OpenMRS
    description: OpenMRS 3
    port: 80
    onOpen: open-browser
  - name: Odoo
    description: Odoo
    port: 8069
  - name: Superset
    description: Superset
    port: 8088
  - name: OpenELIS
    description: OpenELIS
    port: 8443
